"""Command line interface for TripPlanner."""

from __future__ import annotations

import argparse
import json
from typing import Sequence

from tripplanner.telemetry import start_span


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="tripplanner",
        description="TripPlanner demo CLI.",
    )
    subparsers = parser.add_subparsers(dest="command")

    demo_parser = subparsers.add_parser(
        "demo",
        help="Run a stub itinerary planner output.",
    )
    demo_parser.add_argument("query", help="Natural-language trip query.")
    return parser


def run_demo(query: str) -> dict[str, str]:
    with start_span("orchestrator.demo"):
        return {
            "status": "stub",
            "query": query,
            "itinerary": "Day 1: Placeholder itinerary generated by scaffold.",
        }


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "demo":
        print(json.dumps(run_demo(args.query), ensure_ascii=True))
        return 0

    parser.print_help()
    return 0
